// src/pages/ProductDetails.jsx
import React, { useState } from "react";
import { useParams, Link } from "react-router-dom";
import { 
  Settings, UploadCloud, ArrowUpDown, EyeOff, LayoutTemplate, 
  Map as MapIcon, Info, Link2, Share2, Users, Globe, Video, 
  Wand2, Image as ImageIcon, Monitor, CheckCircle2, ChevronDown, Menu,
  CheckSquare, Square, Trash2, Download, Edit3, X, Maximize, Move
} from "lucide-react";

export default function ProductDetails() {
  const { id } = useParams();
  const [activeTab, setActiveTab] = useState("Toureinstellungen");
  const [previewImage, setPreviewImage] = useState(null);
  const [isEditorMenuOpen, setIsEditorMenuOpen] = useState(false);
  
  const menuItems = [
    { title: "Toureinstellungen", icon: Settings },
    { title: "Upload", icon: UploadCloud },
    { title: "Sortieren", icon: ArrowUpDown },
    { title: "Verpixeln", icon: EyeOff },
    { title: "Bereiche", icon: LayoutTemplate },
    { title: "Grundrisspläne", icon: MapIcon },
    { title: "Info-Inhalte", icon: Info },
    { title: "Verknüpfen", icon: Link2 },
    { title: "Freigabe", icon: Share2 },
    { title: "Kundenverwaltung", icon: Users },
    { title: "Veröffentlichen", icon: Globe },
    { title: "Sichtbeschränkung", icon: EyeOff },
    { title: "AI Video", icon: Video },
    { title: "AI Grundriss (BETA)", icon: MapIcon },
    { title: "KI-Bildverbesserung (BETA)", icon: Wand2 },
  ];

  const settingsCheckboxes = [
    { label: "Panoramen automatisch langsam drehen", checked: true },
    { label: "Zoom zulassen", checked: false },
    { label: "Widerrufserklärung vorschalten", checked: false },
    { label: "Willkommenspopup anzeigen", checked: true },
    { label: "Social Media Buttons anzeigen", checked: true },
    { label: "Virtual Reality zulassen", checked: true },
    { label: "Vermessung aktivieren", checked: false },
  ];

  const uploadedImages = [
    { id: 1, name: "R0010002.JPG", thumb: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=1200" },
    { id: 2, name: "360_edited.jpg", thumb: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=1200" },
  ];

  const renderToureinstellungen = () => (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div className="space-y-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-5">   
          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Freigabe-Status</label>
            <div className="relative">
              <select className="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                <option>Öffentlich</option>
                <option>Privat</option>
              </select>
              <ChevronDown className="absolute right-3 top-3 text-gray-400 pointer-events-none" size={18} />
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Tourname<span className="text-orange-500">*</span></label>
            <input 
              type="text" 
              defaultValue="Robby Testing"
              className="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors"
            />
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Objekt ID</label>
            <input 
              type="text" 
              placeholder="Objekt ID"
              className="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors"
            />
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Ansprechpartner</label>
            <div className="relative">
              <select className="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                <option>Kein Ansprechpartner</option>
              </select>
              <ChevronDown className="absolute right-3 top-3 text-gray-400 pointer-events-none" size={18} />
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Adresse <span className="text-gray-400 font-normal">(wird nicht öffentlich angezeigt)</span></label>
            <textarea 
              rows="3"
              className="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors resize-none"
            ></textarea>
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-1.5">Exposé Informationen</label>
            <div className="relative mb-3">
              <select disabled className="w-full appearance-none bg-gray-100 border border-gray-200 text-gray-400 py-2.5 px-4 rounded-xl cursor-not-allowed">
                <option>Kein Exposé</option>
              </select>
              <ChevronDown className="absolute right-3 top-3 text-gray-300 pointer-events-none" size={18} />
            </div>
            <div className="bg-blue-50 text-blue-800 text-sm p-4 rounded-xl flex gap-3 items-start">
              <Info size={20} className="shrink-0 text-blue-500 mt-0.5" />
              <p>Sie haben noch keine Info-Inhalte für diese Tour erstellt. Legen Sie Ihren Exposé-Text im Menüpunkt "Info-Inhalte" an.</p>
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-4">
          <label className="block text-sm font-bold text-gray-700">Hintergrundmusik *</label>
          <div className="space-y-3">
            <label className="flex items-center gap-3 cursor-pointer">
              <div className="w-5 h-5 rounded-full border-2 border-orange-500 flex items-center justify-center">
                <div className="w-2.5 h-2.5 bg-orange-500 rounded-full"></div>
              </div>
              <span className="text-sm text-gray-700 font-medium">Keine Hintergrundmusik</span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer opacity-50">
              <div className="w-5 h-5 rounded-full border-2 border-gray-300 flex items-center justify-center"></div>
              <span className="text-sm text-gray-700 font-medium">FEEL Good</span>
            </label>
          </div>
        </div>
      </div>

      <div className="space-y-6">
        {/* Einstellungen Checkboxes */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <label className="block text-sm font-bold text-gray-700 mb-4">Einstellungen</label>
          <div className="space-y-4">
            {settingsCheckboxes.map((item, idx) => (
              <label key={idx} className="flex items-center gap-3 cursor-pointer group">
                {item.checked ? (
                  <div className="text-orange-500 shrink-0">
                    <CheckSquare size={22} className="fill-orange-100" />
                  </div>
                ) : (
                  <div className="text-gray-300 group-hover:text-gray-400 shrink-0 transition-colors">
                    <Square size={22} />
                  </div>
                )}
                <span className="text-sm text-gray-700">{item.label}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Größe des Stativ-Stickers */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <label className="block text-sm font-bold text-gray-700 mb-1.5">Größe des Stativ-Stickers <span className="text-gray-400 font-normal">(VR und Messmodus)</span></label>
          <div className="relative">
            <select className="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
              <option>Kleiner Sticker (FEELESTATE Monopod)</option>
            </select>
            <ChevronDown className="absolute right-3 top-3 text-gray-400 pointer-events-none" size={18} />
          </div>
        </div>

        {/* Tour-Zuweisung */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <label className="block text-sm font-bold text-gray-700 mb-1.5">Tour-Zuweisung</label>
          <div className="relative">
            <select className="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
              <option>Kein Teammitglied für die Verteilung</option>
            </select>
            <ChevronDown className="absolute right-3 top-3 text-gray-400 pointer-events-none" size={18} />
          </div>
        </div>

        {/* Button-Typ */}
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
          <label className="block text-sm font-bold text-gray-700 mb-4">Button-Typ für Navigationselemente</label>
          <div className="flex gap-4">
            <button className="w-20 h-20 rounded-xl border-2 border-orange-500 bg-orange-50 flex items-center justify-center relative overflow-hidden transition-all shadow-sm">
              <div className="w-10 h-10 border-2 border-orange-500 bg-white rounded-full flex items-center justify-center">
                <span className="w-6 h-6 border-b-2 border-r-2 border-orange-500 transform rotate-45 -mt-1"></span>
              </div>
              <div className="absolute top-1 right-1 bg-orange-500 rounded-full text-white">
                <CheckCircle2 size={16} />
              </div>
            </button>
            <button className="w-20 h-20 rounded-xl border-2 border-gray-200 bg-transparent flex items-center justify-center transition-all hover:bg-gray-50 shadow-sm opacity-60 hover:opacity-100">
              <div className="w-12 h-12 bg-gray-300 rounded-full flex items-center justify-center opacity-70">
                <span className="w-5 h-5 border-t-4 border-l-4 border-white transform rotate-45 ml-1 mt-1"></span>
              </div>
            </button>
          </div>
        </div>
      </div>
    </div>
  );

  const renderUpload = () => (
    <div className="space-y-6">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-2">Upload</h2>
        <p className="text-gray-500 text-sm">Verwalten Sie die Einstellungen Ihrer virtuellen Tour</p>
      </div>

      <div className="flex flex-wrap gap-8">
        
        {/* Upload Dropzone */}
        <div className="w-full max-w-[320px] h-[220px] border-2 border-dashed border-orange-300 bg-orange-50/40 rounded-3xl flex flex-col items-center justify-center cursor-pointer hover:bg-orange-50 hover:border-orange-400 transition-all group">
          <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center shadow-sm mb-4 relative group-hover:scale-110 transition-transform">
            <ImageIcon size={28} className="text-orange-500" />
            <div className="absolute right-0 bottom-0 bg-green-500 rounded-full border-2 border-white w-6 h-6 flex items-center justify-center">
              <span className="text-white text-[14px] font-bold leading-none -mt-0.5">+</span>
            </div>
          </div>
          <p className="font-bold text-orange-500 px-6 text-center leading-snug">
            Datei wählen oder ins Fenster<br/>ziehen
          </p>
        </div>

        {/* Uploaded Images */}
        {uploadedImages.map((img) => (
          <div key={img.id} className="w-full max-w-[320px] space-y-3">
            <div 
              className="h-[220px] rounded-3xl bg-cover bg-center shadow-sm border border-gray-200 relative group cursor-pointer overflow-hidden"
              style={{ backgroundImage: `url(${img.thumb})` }}
              onClick={() => setPreviewImage(img)}
            >
              {/* Image Overlay */}
              <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300"></div>
              
              {/* Float action buttons */}
              <div className="absolute top-4 right-4 flex gap-2 translate-y-[-10px] opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-300">
                <button 
                  className="w-9 h-9 rounded-full bg-white text-orange-500 flex items-center justify-center shadow-md hover:bg-orange-500 hover:text-white transition-colors"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Trash2 size={16} />
                </button>
                <button 
                  className="w-9 h-9 rounded-full bg-white text-orange-500 flex items-center justify-center shadow-md hover:bg-orange-500 hover:text-white transition-colors"
                  onClick={(e) => e.stopPropagation()}
                >
                  <Download size={16} />
                </button>
              </div>
              
              {/* 360 preview badge */}
              <div className="absolute bottom-4 left-4 bg-black/60 backdrop-blur-md rounded-lg px-2.5 py-1.5 flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
                <Move size={14} className="text-white" />
                <span className="text-[11px] text-white font-bold uppercase tracking-widest">360° Preview</span>
              </div>
            </div>
            
            <div className="flex items-center gap-2 group cursor-pointer w-max pl-1">
              <p className="text-gray-900 font-bold text-[15px] group-hover:text-orange-500 transition-colors">
                {img.name}
              </p>
              <Edit3 size={14} className="text-orange-300 stroke-[2.5px] group-hover:text-orange-500 transition-colors" />
            </div>
          </div>
        ))}
      </div>
    </div>
  );

  return (
    <div className="flex flex-col lg:flex-row min-h-[calc(100vh-80px)] bg-gray-50 border-t border-gray-100 relative">
      {/* Mobile top bar for editor menu control */}
      <div className="lg:hidden sticky top-20 z-20 bg-white/95 backdrop-blur-md border-b border-gray-200 px-4 py-3">
        <button
          onClick={() => setIsEditorMenuOpen(true)}
          className="w-full flex items-center justify-between gap-3 px-4 py-3 rounded-xl border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 transition-colors"
        >
          <span className="flex items-center gap-2.5 min-w-0">
            <Menu size={18} className="text-orange-500 shrink-0" />
            <span className="font-semibold truncate">Editor-Menü: {activeTab}</span>
          </span>
          <span className="text-xs font-semibold text-orange-500 uppercase tracking-wide">Öffnen</span>
        </button>
      </div>

      {/* Mobile editor menu drawer */}
      {isEditorMenuOpen && (
        <div className="lg:hidden fixed inset-0 z-40">
          <div
            className="absolute inset-0 bg-black/40"
            onClick={() => setIsEditorMenuOpen(false)}
          />
          <aside className="absolute top-20 left-0 h-[calc(100vh-80px)] w-[88%] max-w-sm bg-white border-r border-gray-200 shadow-xl flex flex-col">
            <div className="p-4 border-b border-gray-100 flex items-start justify-between gap-3">
              <div className="min-w-0">
                <h2 className="text-lg font-bold text-gray-800 tracking-tight leading-tight">
                  Editor <span className="block text-gray-400 font-medium text-sm">{activeTab}</span>
                </h2>
                <p className="text-orange-500 font-semibold mt-2 text-base">Robby Testing</p>
              </div>
              <button
                onClick={() => setIsEditorMenuOpen(false)}
                className="w-9 h-9 rounded-lg border border-gray-200 text-gray-500 hover:text-gray-700 hover:bg-gray-50 flex items-center justify-center shrink-0"
                aria-label="Close editor menu"
              >
                <X size={18} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto py-2">
              <nav className="flex flex-col gap-1 px-2">
                {menuItems.map((item, idx) => {
                  const isActive = activeTab === item.title;
                  return (
                    <button
                      key={idx}
                      onClick={() => {
                        setActiveTab(item.title);
                        setIsEditorMenuOpen(false);
                      }}
                      className={`flex items-center w-full gap-3 px-4 py-3 rounded-xl text-left transition-colors text-sm font-medium ${
                        isActive
                          ? "bg-orange-50 text-orange-600"
                          : "text-gray-600 hover:bg-gray-50 hover:text-gray-900"
                      }`}
                    >
                      <item.icon size={18} className={isActive ? "text-orange-500" : "text-gray-400"} />
                      {item.title}
                    </button>
                  );
                })}
              </nav>
            </div>

            <div className="p-4 border-t border-gray-100 bg-white">
              <a
                href="#"
                className="flex items-center gap-3 px-4 py-3 text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-xl transition-colors"
              >
                <Monitor size={18} className="text-gray-400" />
                Tour im Browser ansehen
              </a>
            </div>
          </aside>
        </div>
      )}
      
      {/* Secondary Sidebar (Editor Menu) */}
      <aside className="hidden lg:flex w-full lg:w-72 bg-white border-b lg:border-b-0 lg:border-r border-gray-200 shrink-0 flex-col h-auto lg:h-[calc(100vh-80px)] lg:sticky lg:top-20 z-10">
        <div className="p-4 sm:p-6 border-b border-gray-100">
          <h2 className="text-lg sm:text-xl font-bold text-gray-800 tracking-tight leading-tight">
            Editor <span className="block sm:inline text-gray-400 font-medium text-sm sm:ml-1">{activeTab}</span>
          </h2>
          <p className="text-orange-500 font-semibold mt-2 text-base sm:text-lg">Robby Testing</p>
        </div>
        
        <div className="flex-1 overflow-x-auto lg:overflow-y-auto py-2 lg:py-4">
          <nav className="flex lg:flex-col gap-2 lg:gap-1 px-3 lg:px-0 min-w-max lg:min-w-0">
            {menuItems.map((item, idx) => {
              const isActive = activeTab === item.title;
              return (
                <button 
                  key={idx}
                  onClick={() => setActiveTab(item.title)}
                  className={`flex items-center lg:w-full gap-2.5 lg:gap-3 px-4 lg:px-6 py-2.5 lg:py-3 rounded-xl lg:rounded-none whitespace-nowrap transition-colors text-sm font-medium shrink-0 ${
                    isActive 
                      ? "bg-orange-50 text-orange-600 lg:border-l-4 lg:border-orange-500"
                      : "text-gray-600 hover:bg-gray-50 hover:text-gray-900 lg:border-l-4 lg:border-transparent"
                  }`}
                >
                  <item.icon size={18} className={isActive ? "text-orange-500" : "text-gray-400"} />
                  {item.title}
                </button>
              );
            })}
          </nav>
        </div>
        
        <div className="p-4 border-t border-gray-100 bg-white">
          <a href="#" className="flex items-center gap-3 px-4 py-3 text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-xl transition-colors">
            <Monitor size={18} className="text-gray-400" />
            Tour im Browser ansehen
          </a>
        </div>
      </aside>

      {/* Main Form Content */}
      <div className="flex-1 p-4 sm:p-6 lg:p-10 w-full flex justify-center">
        <div className="w-full max-w-6xl">
          {activeTab === "Toureinstellungen" ? renderToureinstellungen() : null}
          {activeTab === "Upload" ? renderUpload() : null}
          {activeTab !== "Toureinstellungen" && activeTab !== "Upload" ? (
            <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed border-gray-200 rounded-3xl bg-gray-50 mt-10">
              <Wand2 size={48} className="text-gray-300 mb-4" />
              <h3 className="text-xl font-bold text-gray-500">{activeTab}</h3>
              <p className="text-gray-400 mt-2">Dieser Bereich wird gerade entwickelt.</p>
            </div>
          ) : null}
        </div>
      </div>

      {/* 360 Image Preview Modal */}
      {previewImage && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 backdrop-blur-md">
          {/* Close button */}
          <button 
            className="absolute top-4 right-4 sm:top-6 sm:right-6 w-11 h-11 sm:w-12 sm:h-12 bg-white/10 hover:bg-white/20 text-white rounded-full flex items-center justify-center transition-colors shadow-lg z-50 backdrop-blur-sm"
            onClick={() => setPreviewImage(null)}
          >
            <X size={24} />
          </button>
          
          <div className="absolute top-4 left-4 sm:top-6 sm:left-6 z-50 flex items-center gap-2.5 sm:gap-3 max-w-[calc(100%-7rem)] sm:max-w-none">
            <div className="w-9 h-9 sm:w-10 sm:h-10 bg-orange-500 rounded-full flex items-center justify-center shadow-lg shrink-0">
              <Move size={20} className="text-white" />
            </div>
            <div className="min-w-0">
              <p className="text-white font-bold text-base sm:text-lg truncate">{previewImage.name}</p>
              <p className="text-orange-400 text-xs font-bold uppercase tracking-widest">360° Interactive Preview</p>
            </div>
          </div>
          
          {/* Mock 360 Interactive Container */}
          <div className="w-full h-full relative cursor-grab active:cursor-grabbing overflow-x-auto overflow-y-hidden hide-scrollbar flex items-center">
             {/* We simulate a 360 image by stretching the background width very wide */}
             <div 
               className="min-w-[200vw] sm:min-w-[150vw] h-[70vh] sm:h-[85vh] bg-cover bg-center bg-no-repeat transition-transform"
               style={{ 
                 backgroundImage: `url(${previewImage.thumb})`,
                 backgroundSize: '100% 100%'
               }}
             />
          </div>
          
          <div className="absolute bottom-6 sm:bottom-10 left-1/2 transform -translate-x-1/2 bg-black/50 backdrop-blur-md border border-white/10 px-4 sm:px-6 py-2.5 sm:py-3 rounded-full flex gap-3 sm:gap-6 text-white z-50 shadow-2xl items-center pointer-events-none">
            <Maximize size={18} className="opacity-70" />
            <span className="font-semibold text-xs sm:text-sm tracking-wide whitespace-nowrap">Drag to look around</span>
          </div>
        </div>
      )}
    </div>
  );
}

// src/app/pages/product-details/product-details.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideArrowDownToLine,
  lucideArrowUpDown,
  lucideCheck,
  lucideChevronDown,
  lucideEyeOff,
  lucideGlobe,
  lucideImage,
  lucideInfo,
  lucideLayoutTemplate,
  lucideLink2,
  lucideMap,
  lucideMaximize,
  lucideMenu,
  lucideMonitor,
  lucideMove,
  lucidePencil,
  lucideSettings,
  lucideShare2,
  lucideSquareCheck,
  lucideSquare,
  lucideTrash2,
  lucideUpload,
  lucideUsers,
  lucideVideo,
  lucideWandSparkles,
  lucideX,
} from '@ng-icons/lucide';

type UploadImage = { id: number; name: string; thumb: string };
type MenuItem = { title: string; icon: string };
type SettingCheckbox = { label: string; checked: boolean };

@Component({
  selector: 'app-product-details',
  standalone: true,
  imports: [CommonModule, NgIcon],
  providers: [
    provideIcons({
      lucideMenu,
      lucideX,
      lucideMonitor,
      lucideSettings,
      lucideUpload,
      lucideArrowUpDown,
      lucideEyeOff,
      lucideLayoutTemplate,
      lucideMap,
      lucideInfo,
      lucideLink2,
      lucideShare2,
      lucideUsers,
      lucideGlobe,
      lucideVideo,
      lucideWandSparkles,
      lucideChevronDown,
      lucideSquareCheck,
      lucideSquare,
      lucideImage,
      lucideTrash2,
      lucideArrowDownToLine,
      lucidePencil,
      lucideMove,
      lucideMaximize,
      lucideCheck,
    }),
  ],
  templateUrl: './product-details.component.html',
})
export class ProductDetailsComponent {
  readonly id: string | null;
  activeTab = 'Toureinstellungen';
  isEditorMenuOpen = false;
  previewImage: UploadImage | null = null;

  readonly menuItems: MenuItem[] = [
    { title: 'Toureinstellungen', icon: 'lucideSettings' },
    { title: 'Upload', icon: 'lucideUpload' },
    { title: 'Sortieren', icon: 'lucideArrowUpDown' },
    { title: 'Verpixeln', icon: 'lucideEyeOff' },
    { title: 'Bereiche', icon: 'lucideLayoutTemplate' },
    { title: 'Grundrissplaene', icon: 'lucideMap' },
    { title: 'Info-Inhalte', icon: 'lucideInfo' },
    { title: 'Verknuepfen', icon: 'lucideLink2' },
    { title: 'Freigabe', icon: 'lucideShare2' },
    { title: 'Kundenverwaltung', icon: 'lucideUsers' },
    { title: 'Veroeffentlichen', icon: 'lucideGlobe' },
    { title: 'Sichtbeschraenkung', icon: 'lucideEyeOff' },
    { title: 'AI Video', icon: 'lucideVideo' },
    { title: 'AI Grundriss (BETA)', icon: 'lucideMap' },
    { title: 'KI-Bildverbesserung (BETA)', icon: 'lucideWandSparkles' },
  ];

  readonly settingsCheckboxes: SettingCheckbox[] = [
    { label: 'Panoramen automatisch langsam drehen', checked: true },
    { label: 'Zoom zulassen', checked: false },
    { label: 'Widerrufserklaerung vorschalten', checked: false },
    { label: 'Willkommenspopup anzeigen', checked: true },
    { label: 'Social Media Buttons anzeigen', checked: true },
    { label: 'Virtual Reality zulassen', checked: true },
    { label: 'Vermessung aktivieren', checked: false },
  ];

  readonly uploadedImages: UploadImage[] = [
    {
      id: 1,
      name: 'R0010002.JPG',
      thumb: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=1200',
    },
    {
      id: 2,
      name: '360_edited.jpg',
      thumb: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=1200',
    },
  ];

  constructor(route: ActivatedRoute) {
    this.id = route.snapshot.paramMap.get('id');
  }

  selectTab(tab: string | MenuItem): void {
    this.activeTab = typeof tab === 'string' ? tab : tab.title;
    this.isEditorMenuOpen = false;
  }
}

<div class="flex flex-col lg:flex-row min-h-[calc(100vh-80px)] bg-gray-50 border-t border-gray-100 relative">
  <div class="lg:hidden sticky top-20 z-20 bg-white/95 backdrop-blur-md border-b border-gray-200 px-4 py-3">
    <button
      (click)="isEditorMenuOpen = true"
      class="w-full flex items-center justify-between gap-3 px-4 py-3 rounded-xl border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 transition-colors"
    >
      <span class="flex items-center gap-2.5 min-w-0">
        <ng-icon name="lucideMenu" class="text-orange-500 text-[18px] shrink-0"></ng-icon>
        <span class="font-semibold truncate">Editor-Menue: {{ activeTab }}</span>
      </span>
      <span class="text-xs font-semibold text-orange-500 uppercase tracking-wide">Oeffnen</span>
    </button>
  </div>

  <div *ngIf="isEditorMenuOpen" class="lg:hidden fixed inset-0 z-40">
    <div class="absolute inset-0 bg-black/40" (click)="isEditorMenuOpen = false"></div>
    <aside class="absolute top-20 left-0 h-[calc(100vh-80px)] w-[88%] max-w-sm bg-white border-r border-gray-200 shadow-xl flex flex-col">
      <div class="p-4 border-b border-gray-100 flex items-start justify-between gap-3">
        <div class="min-w-0">
          <h2 class="text-lg font-bold text-gray-800 tracking-tight leading-tight">Editor</h2>
                <p class="text-orange-500 font-semibold mt-2 text-base">Robby Testing</p>
        </div>
        <button (click)="isEditorMenuOpen = false" class="w-9 h-9 rounded-lg border border-gray-200 text-gray-500 hover:bg-gray-50 flex items-center justify-center"><ng-icon name="lucideX" class="text-[18px]"></ng-icon></button>
      </div>

      <div class="flex-1 overflow-y-auto py-2">
        <nav class="flex flex-col gap-1 px-2">
          <button
            *ngFor="let item of menuItems"
            (click)="selectTab(item)"
            class="flex items-center w-full gap-3 px-4 py-3 rounded-xl text-left transition-colors text-sm font-medium"
                  [ngClass]="activeTab === item.title ? 'bg-orange-50 text-orange-600' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'"
          >
                  <ng-icon [name]="item.icon" class="text-[18px] shrink-0" [ngClass]="activeTab === item.title ? 'text-orange-500' : 'text-gray-400'"></ng-icon>
                  {{ item.title }}
          </button>
        </nav>
      </div>

            <div class="p-4 border-t border-gray-100 bg-white">
              <a href="#" class="flex items-center gap-3 px-4 py-3 text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-xl transition-colors">
                <ng-icon name="lucideMonitor" class="text-[18px] text-gray-400"></ng-icon>
                Tour im Browser ansehen
              </a>
            </div>
    </aside>
  </div>

  <aside class="hidden lg:flex w-full lg:w-72 bg-white border-b lg:border-b-0 lg:border-r border-gray-200 shrink-0 flex-col h-auto lg:h-[calc(100vh-80px)] lg:sticky lg:top-20 z-10">
    <div class="p-4 sm:p-6 border-b border-gray-100">
      <h2 class="text-lg sm:text-xl font-bold text-gray-800 tracking-tight leading-tight">
        Editor <span class="block sm:inline text-gray-400 font-medium text-sm sm:ml-1">{{ activeTab }}</span>
      </h2>
      <p class="text-orange-500 font-semibold mt-2 text-base sm:text-lg">Robby Testing</p>
    </div>

    <div class="flex-1 overflow-x-auto lg:overflow-y-auto py-2 lg:py-4">
      <nav class="flex lg:flex-col gap-2 lg:gap-1 px-3 lg:px-0 min-w-max lg:min-w-0">
        <button
          *ngFor="let item of menuItems"
          (click)="selectTab(item)"
          class="flex items-center lg:w-full gap-2.5 lg:gap-3 px-4 lg:px-6 py-2.5 lg:py-3 rounded-xl lg:rounded-none whitespace-nowrap transition-colors text-sm font-medium shrink-0"
          [ngClass]="activeTab === item.title ? 'bg-orange-50 text-orange-600 lg:border-l-4 lg:border-orange-500' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900 lg:border-l-4 lg:border-transparent'"
        >
          <ng-icon [name]="item.icon" class="text-[18px] shrink-0" [ngClass]="activeTab === item.title ? 'text-orange-500' : 'text-gray-400'"></ng-icon>
          {{ item.title }}
        </button>
      </nav>
    </div>

    <div class="p-4 border-t border-gray-100 bg-white">
      <a href="#" class="flex items-center gap-3 px-4 py-3 text-sm font-medium text-gray-600 hover:text-gray-900 hover:bg-gray-50 rounded-xl transition-colors">
        <ng-icon name="lucideMonitor" class="text-[18px] text-gray-400"></ng-icon>
        Tour im Browser ansehen
      </a>
    </div>
  </aside>

  <div class="flex-1 p-4 sm:p-6 lg:p-10 w-full flex justify-center">
    <div class="w-full max-w-6xl">
      <div *ngIf="activeTab === 'Toureinstellungen'" class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div class="space-y-6">
          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-5">
            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Freigabe-Status</label>
              <div class="relative">
                <select class="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                  <option>Oeffentlich</option>
                  <option>Privat</option>
                </select>
                <ng-icon name="lucideChevronDown" class="absolute right-3 top-3 text-gray-400 pointer-events-none text-[18px]"></ng-icon>
              </div>
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Tourname <span class="text-orange-500">*</span></label>
              <input type="text" value="Robby Testing" class="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors" />
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Objekt ID</label>
              <input type="text" placeholder="Objekt ID" class="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors" />
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Ansprechpartner</label>
              <div class="relative">
                <select class="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                  <option>Kein Ansprechpartner</option>
                </select>
                <ng-icon name="lucideChevronDown" class="absolute right-3 top-3 text-gray-400 pointer-events-none text-[18px]"></ng-icon>
              </div>
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Adresse <span class="text-gray-400 font-normal">(wird nicht oeffentlich angezeigt)</span></label>
              <textarea rows="3" class="w-full bg-white border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors resize-none"></textarea>
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1.5">Expose Informationen</label>
              <div class="relative mb-3">
                <select disabled class="w-full appearance-none bg-gray-100 border border-gray-200 text-gray-400 py-2.5 px-4 rounded-xl cursor-not-allowed">
                  <option>Kein Expose</option>
                </select>
                <ng-icon name="lucideChevronDown" class="absolute right-3 top-3 text-gray-300 pointer-events-none text-[18px]"></ng-icon>
              </div>
              <div class="bg-blue-50 text-blue-800 text-sm p-4 rounded-xl flex gap-3 items-start">
                <ng-icon name="lucideInfo" class="shrink-0 text-blue-500 mt-0.5 text-[18px]"></ng-icon>
                <p>Sie haben noch keine Info-Inhalte fuer diese Tour erstellt. Legen Sie Ihren Expose-Text im Menuepunkt "Info-Inhalte" an.</p>
              </div>
            </div>
          </div>

          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 space-y-4">
            <label class="block text-sm font-bold text-gray-700">Hintergrundmusik *</label>
            <div class="space-y-3">
              <label class="flex items-center gap-3 cursor-pointer">
                <div class="w-5 h-5 rounded-full border-2 border-orange-500 flex items-center justify-center">
                  <div class="w-2.5 h-2.5 bg-orange-500 rounded-full"></div>
                </div>
                <span class="text-sm text-gray-700 font-medium">Keine Hintergrundmusik</span>
              </label>
              <label class="flex items-center gap-3 cursor-pointer opacity-50">
                <div class="w-5 h-5 rounded-full border-2 border-gray-300 flex items-center justify-center"></div>
                <span class="text-sm text-gray-700 font-medium">FEEL Good</span>
              </label>
            </div>
          </div>
        </div>

        <div class="space-y-6">
          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
            <label class="block text-sm font-bold text-gray-700 mb-4">Einstellungen</label>
            <div class="space-y-4">
              <label *ngFor="let item of settingsCheckboxes" class="flex items-center gap-3 cursor-pointer group">
                <ng-icon *ngIf="item.checked" name="lucideSquareCheck" class="text-orange-500 shrink-0 text-[20px]"></ng-icon>
                <ng-icon *ngIf="!item.checked" name="lucideSquare" class="text-gray-300 group-hover:text-gray-400 shrink-0 transition-colors text-[20px]"></ng-icon>
                <span class="text-sm text-gray-700">{{ item.label }}</span>
              </label>
            </div>
          </div>

          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
            <label class="block text-sm font-bold text-gray-700 mb-1.5">Groesse des Stativ-Stickers <span class="text-gray-400 font-normal">(VR und Messmodus)</span></label>
            <div class="relative">
              <select class="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                <option>Kleiner Sticker (FEELESTATE Monopod)</option>
              </select>
              <ng-icon name="lucideChevronDown" class="absolute right-3 top-3 text-gray-400 pointer-events-none text-[18px]"></ng-icon>
            </div>
          </div>

          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
            <label class="block text-sm font-bold text-gray-700 mb-1.5">Tour-Zuweisung</label>
            <div class="relative">
              <select class="w-full appearance-none bg-gray-50 border border-gray-200 text-gray-700 py-2.5 px-4 rounded-xl focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-500 transition-colors">
                <option>Kein Teammitglied fuer die Verteilung</option>
              </select>
              <ng-icon name="lucideChevronDown" class="absolute right-3 top-3 text-gray-400 pointer-events-none text-[18px]"></ng-icon>
            </div>
          </div>

          <div class="bg-white p-6 rounded-2xl shadow-sm border border-gray-100">
            <label class="block text-sm font-bold text-gray-700 mb-4">Button-Typ fuer Navigationselemente</label>
            <div class="flex gap-4">
              <button class="w-20 h-20 rounded-xl border-2 border-orange-500 bg-orange-50 flex items-center justify-center relative overflow-hidden transition-all shadow-sm">
                <div class="w-10 h-10 border-2 border-orange-500 bg-white rounded-full flex items-center justify-center">
                  <span class="w-6 h-6 border-b-2 border-r-2 border-orange-500 transform rotate-45 -mt-1"></span>
                </div>
                <div class="absolute top-1 right-1 bg-orange-500 rounded-full text-white w-4 h-4 text-[10px] flex items-center justify-center"><ng-icon name="lucideCheck" class="text-[10px]"></ng-icon></div>
              </button>
              <button class="w-20 h-20 rounded-xl border-2 border-gray-200 bg-transparent flex items-center justify-center transition-all hover:bg-gray-50 shadow-sm opacity-60 hover:opacity-100">
                <div class="w-12 h-12 bg-gray-300 rounded-full flex items-center justify-center opacity-70">
                  <span class="w-5 h-5 border-t-4 border-l-4 border-white transform rotate-45 ml-1 mt-1"></span>
                </div>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div *ngIf="activeTab === 'Upload'" class="space-y-6">
        <div class="mb-8">
          <h2 class="text-3xl font-bold text-gray-900 mb-2">Upload</h2>
          <p class="text-gray-500 text-sm">Verwalten Sie die Einstellungen Ihrer virtuellen Tour</p>
        </div>

        <div class="flex flex-wrap gap-8">
          <div class="w-full max-w-[320px] h-[220px] border-2 border-dashed border-orange-300 bg-orange-50/40 rounded-3xl flex flex-col items-center justify-center cursor-pointer hover:bg-orange-50 hover:border-orange-400 transition-all group">
            <div class="w-16 h-16 bg-white rounded-full flex items-center justify-center shadow-sm mb-4 relative group-hover:scale-110 transition-transform">
              <ng-icon name="lucideImage" class="text-orange-500 text-[28px]"></ng-icon>
              <div class="absolute right-0 bottom-0 bg-green-500 rounded-full border-2 border-white w-6 h-6 flex items-center justify-center">
                <span class="text-white text-[14px] font-bold leading-none -mt-0.5">+</span>
              </div>
            </div>
            <p class="font-bold text-orange-500 px-6 text-center leading-snug">Datei waehlen oder ins Fenster<br />ziehen</p>
          </div>

          <div *ngFor="let img of uploadedImages" class="w-full max-w-[320px] space-y-3">
            <div
              class="h-[220px] rounded-3xl bg-cover bg-center shadow-sm border border-gray-200 relative group cursor-pointer overflow-hidden"
              [style.background-image]="'url(' + img.thumb + ')'"
              (click)="previewImage = img"
            >
              <div class="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300"></div>
              <div class="absolute top-4 right-4 flex gap-2 translate-y-[-10px] opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-300">
                <button class="w-9 h-9 rounded-full bg-white text-orange-500 flex items-center justify-center shadow-md hover:bg-orange-500 hover:text-white transition-colors" (click)="$event.stopPropagation()"><ng-icon name="lucideTrash2" class="text-[16px]"></ng-icon></button>
                <button class="w-9 h-9 rounded-full bg-white text-orange-500 flex items-center justify-center shadow-md hover:bg-orange-500 hover:text-white transition-colors" (click)="$event.stopPropagation()"><ng-icon name="lucideArrowDownToLine" class="text-[16px]"></ng-icon></button>
              </div>
              <div class="absolute bottom-4 left-4 bg-black/60 backdrop-blur-md rounded-lg px-2.5 py-1.5 flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
                <ng-icon name="lucideMove" class="text-[14px] text-white"></ng-icon>
                <span class="text-[11px] text-white font-bold uppercase tracking-widest">360 Interactive Preview</span>
              </div>
            </div>

            <div class="flex items-center gap-2 group cursor-pointer w-max pl-1">
              <p class="text-gray-900 font-bold text-[15px] group-hover:text-orange-500 transition-colors">{{ img.name }}</p>
              <ng-icon name="lucidePencil" class="text-orange-300 text-[14px] group-hover:text-orange-500 transition-colors"></ng-icon>
            </div>
          </div>
        </div>
      </div>

      <div *ngIf="activeTab !== 'Toureinstellungen' && activeTab !== 'Upload'" class="flex flex-col items-center justify-center h-64 border-2 border-dashed border-gray-200 rounded-3xl bg-gray-50 mt-10">
        <h3 class="text-xl font-bold text-gray-500">{{ activeTab }}</h3>
        <p class="text-gray-400 mt-2">Dieser Bereich wird gerade entwickelt.</p>
      </div>
    </div>
  </div>

  <div *ngIf="previewImage" class="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 backdrop-blur-md">
    <button
      class="absolute top-4 right-4 sm:top-6 sm:right-6 w-11 h-11 sm:w-12 sm:h-12 bg-white/10 hover:bg-white/20 text-white rounded-full flex items-center justify-center"
      (click)="previewImage = null"
    >
      <ng-icon name="lucideX" class="text-[24px]"></ng-icon>
    </button>

    <div class="absolute top-4 left-4 sm:top-6 sm:left-6 z-50 flex items-center gap-2.5 sm:gap-3 max-w-[calc(100%-7rem)] sm:max-w-none">
      <div class="w-9 h-9 sm:w-10 sm:h-10 bg-orange-500 rounded-full flex items-center justify-center shadow-lg shrink-0 text-white text-xs"><ng-icon name="lucideMove" class="text-[20px]"></ng-icon></div>
      <div class="min-w-0">
        <p class="text-white font-bold text-base sm:text-lg truncate">{{ previewImage.name }}</p>
        <p class="text-orange-400 text-xs font-bold uppercase tracking-widest">Interactive Preview</p>
      </div>
    </div>

    <div class="w-full h-full relative cursor-grab overflow-x-auto overflow-y-hidden hide-scrollbar flex items-center">
      <div class="min-w-[200vw] sm:min-w-[150vw] h-[70vh] sm:h-[85vh] bg-cover bg-center bg-no-repeat" [style.background-image]="'url(' + previewImage!.thumb + ')'" [style.background-size]="'100% 100%'">
      </div>
    </div>

    <div class="absolute bottom-6 sm:bottom-10 left-1/2 transform -translate-x-1/2 bg-black/50 backdrop-blur-md border border-white/10 px-4 sm:px-6 py-2.5 sm:py-3 rounded-full flex gap-3 sm:gap-6 text-white z-50 shadow-2xl items-center pointer-events-none">
      <ng-icon name="lucideMaximize" class="text-[18px] opacity-70"></ng-icon>
      <span class="font-semibold text-xs sm:text-sm tracking-wide whitespace-nowrap">Drag to look around</span>
    </div>
  </div>
</div>
